apiVersion: v1
kind: Secret
metadata:
  name: driver-service-secrets
  namespace: default
type: Opaque
stringData:
  db-host: postgres
  db-port: "5432"
  db-name: driver_db
  db-username: postgres
  db-password: postgres
  oidc-issuer-uri: http://keycloak:8080/realms/fleet-management-frontend
  jpa-show-sql: "false"
