apiVersion: v1
kind: Secret
metadata:
  name: vehicle-service-secrets
  namespace: default
type: Opaque
stringData:
  db-host: postgres
  db-port: "5432"
  db-name: vehicle_db
  db-username: postgres
  db-password: postgres
  jwt-authority: http://keycloak:8080/realms/fleet-management
  cors-origins: "*"
