apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fleet-management

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - istio/virtualservice.yaml
  - istio/destinationrule.yaml
  - istio/peerauthentication.yaml
  - servicemonitor.yaml

commonLabels:
  app.kubernetes.io/name: maintenance-service
  app.kubernetes.io/part-of: fleet-management
  app.kubernetes.io/managed-by: kustomize

images:
  - name: maintenance-service
    newName: harinejan/maintenance-service
    newTag: latest


