apiVersion: v1
kind: Service
metadata:
  name: maintenance-service
  namespace: fleet-management
  labels:
    app: maintenance-service
    service: maintenance-service
spec:
  type: ClusterIP
  ports:
  - port: 5001
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: maintenance-service


