apiVersion: v1
kind: ConfigMap
metadata:
  name: maintenance-service-config
  namespace: default
data:
  FLASK_ENV: "production"
  FLASK_APP: "run.py"
  PORT: "5001"
  HOST: "0.0.0.0"
  CORS_ORIGINS: "*"
  ITEMS_PER_PAGE: "10"
  LOG_LEVEL: "INFO"
  AUTH_DISABLED: "false"
