apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: vehicle-destinationrule
  namespace: default
spec:
  host: vehicle-service
  trafficPolicy:
    tls:
      mode: DISABLE
