apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: driver-service
  namespace: fleet-management
spec:
  selector:
    matchLabels:
      app: driver-service
  mtls:
    mode: STRICT


