apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fleet-management

resources:
  - configmap.yaml
  - ../../infrastructure/ansible/k8s/driver-service-deployment.yaml
  - ../../infrastructure/ansible/k8s/driver-service-service.yaml
  - hpa.yaml
  - istio/virtualservice.yaml
  - istio/destinationrule.yaml
  - istio/peerauthentication.yaml
  - servicemonitor.yaml

commonLabels:
  app.kubernetes.io/name: driver-service
  app.kubernetes.io/part-of: fleet-management
  app.kubernetes.io/managed-by: kustomize

images:
  - name: driver-service
    newName: harinejan/driver-service
    newTag: latest

